Added swift container creation

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 set -e            # fail fast
-set -o pipefail   # don't ignore exit codes when piping output
+set -o pipefail   # dont ignore exit codes when piping output
 # set -x          # enable debugging
 
 build_dir=$1
@@ -43,5 +43,14 @@ status "Building runtime environment."
 mkdir -p $build_dir/.profile.d
 # $HOME is set here https://github.com/cloudfoundry/dea_ng/blob/c2217e5fbcb866c9f4b6fd248b39138a83cbb479/lib/dea/starting/env.rb#L15
 echo "export PATH=\"\$HOME/vendor/jre/bin:\$HOME/bin:\$PATH\";" > $build_dir/.profile.d/jre.sh
+
+status "Importing config from Swift"
+source ~/credentials
+TOKEN=`curl -k -X POST -si https://identity.uk-1.cloud.global.fujitsu.com/v3/auth/tokens -H "Content-Type:application/json" -H "Accept:application/json" -d '{"auth":{"identity":{"methods":["password"],"password":{"user":{"domain":{"name":"'$DOMAIN'"}, "name":"'$USER_NAME'", "password": "'"$USER_PW"'"}}}, "scope": { "project": {"id":"'$PROJECT_ID'"}}}}'`
+
+status "Creating container"
+curl -k -X POST -si https://objectstorage.uk-1.cloud.global.fujitsu.com/v1/AUTH_$PROJECT_ID/jenkins -H "X-Auth-Token: $TOKEN"
+
+
 
 status "Done."
